- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  setPreference: false
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 #5 hrs # Corvax-RoleTime
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlchem
    back: ClothingBackpackMerc
    shoes: ClothingShoesBootsSalvage
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterVestStal
    id: SalvageIDCard
    ears: ClothingHeadsetGrey
    head: ClothingHeadHatWelding
    pocket1: FlashlightSeclite
    pocket2: SurvivalKnife
