- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  setPreference: false
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 #2 hrs # Corvax-RoleTime
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlchem
    back: ClothingBackpackMerc
    shoes: ClothingShoesBootsSalvage
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterVestStal
    id: SalvageIDCard
    ears: ClothingHeadsetGrey
    head: ClothingHeadHatWelding
    pocket1: FlashlightSeclite
    pocket2: SurvivalKnife
