- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  setPreference: false
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 360000 #100 hrs # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at med!
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: MedicalInternGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlchem
    back: ClothingBackpackMerc
    shoes: ClothingShoesBootsSalvage
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterVestStal
    id: SalvageIDCard
    ears: ClothingHeadsetGrey
    head: ClothingHeadHatWelding
    pocket1: FlashlightSeclite
    pocket2: SurvivalKnife
