- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  setPreference: false
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours
    - !type:OverallPlaytimeRequirement
      time: 504000 #140 hrs # Corvax-RoleTime
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: BibleUser

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHamas
    belt: ClothingBeltRPC
    eyes: ClothingEyesVision
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskHamas
    head: ClothingHeadHelmetHamas
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    id: SalvageIDCard
    pocket1: RadioHandheld
    pocket2: Torch
  storage:
    belt:
    - BaseMagazineMP9evil
    - BaseMagazineMP9evil
    - BaseMagazineMP9evil
    - SyringeOpium
