- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 0
  setPreference: true
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomGear
  equipment:
    head: ClothingHeadHatRape
    pocket1: Handcuffs
    pocket2: Handcuffs
    belt: AfganMace
