- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  setPreference: false
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 #6 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 172800 #48 hrs # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityCadetGear
  equipment:
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: BookSpaceLaw # Corvax-HyperLink
  storage:
    back:
    - Flash
    - MagazinePistol
