- type: job
  id: TechnicalAssistant
  canBeAntag: false
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 0
  startingGear: Alchemest
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-alchem
  access:
  - Maintenance

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlchem
    shoes: ClothingShoesBootsSandal
    gloves: ClothingHandsGlovesFingerless
    pocket1: Torch
    pocket2: CombatKnife
    outerClothing: ClothingOuterMantia
    back: ClothingBackpackSatchelLeather
    eyes: ClothingEyesGlassesChemical

- type: startingGear
  id: Alchemest
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlchem
    shoes: ClothingShoesBootsSandal
    gloves: ClothingHandsGlovesFingerless
    pocket1: Torch
    pocket2: RadioHandheldAlchem
    outerClothing: ClothingOuterMantia
    back: ClothingBackpackSatchelLeather
